platform :macos, '10.15'

# Add this line to include the Flutter Podhelper
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), File.dirname(File.dirname(File.realpath(__FILE__))))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
end
